In [1]:
!pip install pandas scikit-learn joblib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

In [ ]:
df = pd.read_csv("diet_training_dataset.csv")

df.head()

,age,gender,weight_kg,height_cm,activity_level,goal,daily_calories
0,56,Female,73,173,Low,Muscle Gain,2044
1,46,Male,91,181,High,Muscle Gain,3578
2,32,Female,89,190,Low,Fat Loss,1707
3,25,Male,46,185,High,Maintain,2618
4,38,Male,71,183,High,Muscle Gain,3320

In [6]:
le_gender = LabelEncoder()
le_activity = LabelEncoder()
le_goal = LabelEncoder()

df["gender"] = le_gender.fit_transform(df["gender"])
df["activity_level"] = le_activity.fit_transform(df["activity_level"])
df["goal"] = le_goal.fit_transform(df["goal"])

df.head()

   age  gender  weight_kg  height_cm  activity_level  goal  daily_calories
0   56       0         73        173               1     2            2044
1   46       1         91        181               0     2            3578
2   32       0         89        190               1     0            1707
3   25       1         46        185               0     1            2618
4   38       1         71        183               0     2            3320

In [7]:
X = df[[
    "age",
    "gender",
    "weight_kg",
    "height_cm",
    "activity_level",
    "goal"
]]

y = df["daily_calories"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
model = RandomForestRegressor(n_estimators=200, random_state=42)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [10]:
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

Mean Absolute Error: 93.77454166666666
R2 Score: 0.9667005124985419

In [11]:
joblib.dump(model, "diet_calorie_model.pkl")

['diet_calorie_model.pkl']

In [12]:
joblib.dump(le_gender, "le_gender.pkl")
joblib.dump(le_activity, "le_activity.pkl")
joblib.dump(le_goal, "le_goal.pkl")

['le_goal.pkl']